"""remove_annotation_project_tags.

Revision ID: 5a5ba50701f7
Revises: 680608e7f7a4
Create Date: 2025-11-10 13:53:55.938828

"""

import sqlalchemy as sa

from alembic import op
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "5a5ba50701f7"
down_revision: Union[str, None] = "680608e7f7a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop the annotation_project_tag association table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("annotation_project_tag")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotation_project_tag",
        sa.Column("annotation_project_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_project_id"],
            ["annotation_project.id"],
            name=op.f("fk_annotation_project_tag_annotation_project_id_annotation_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
            name=op.f("fk_annotation_project_tag_tag_id_tag"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "annotation_project_id",
            "tag_id",
            name=op.f("pk_annotation_project_tag"),
        ),
        sa.UniqueConstraint(
            "annotation_project_id",
            "tag_id",
            name=op.f("uq_annotation_project_tag_annotation_project_id"),
        ),
    )

    # Create indexes using batch mode for SQLite compatibility
    with op.batch_alter_table("annotation_project_tag", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_annotation_project_tag_annotation_project_id"),
            ["annotation_project_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_annotation_project_tag_tag_id"),
            ["tag_id"],
            unique=False,
        )
    # ### end Alembic commands ###
